### DISCUSSION TITLE
Reflector does not delete the mirrors when I delete the source

### DISCUSSION THREAD

**Discussion by dinisinho** [emberstack/kubernetes-reflector#484] [Q&A]
Hello,

I am testing Reflector. I have managed to get Reflector to replicate a secret in a specific namespace when I create or modify it. However, when I delete the original, it does not delete the mirror. From the documentation, I understand that it should do this. I installed it using Helm and here is an example of the secret:

```
apiVersion: v1
data:
  tls.crt: xxxxx
  tls.key: xxxxy
kind: Secret
metadata:
  creationTimestamp: null
  name: wildcard-apps
  namespace: default
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "test"
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "test"
type: kubernetes.io/tls
```

Thank you for your time.

Best regards.
