### ISSUE TITLE
Reflector not reflecting cert-manager certificates to namespaces

### ISSUE THREAD

**Issue by Eagleman7** [emberstack/kubernetes-reflector#225]
With this version 6.0.18 of emberstack/kubernetes-reflector I am not seeing it copy the certificates to the other namespaces. I am using v1.22.2 of kubernetes.

cert-manager config looks like:
```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-example-com
  namespace: cert-manager

spec:
  secretName: wildcard-example-com
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: "public,home"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "example.com"
  dnsNames:
  - 'example.com'
  - '*.examplee.com'
```

This is what describe looks like:

```
kubectl describe certificates -n cert-manager wildcard-example-com
----------------------------------------------------------------------------
Name:         wildcard-example-com
Namespace:    cert-manager
Labels:       kustomize.toolkit.fluxcd.io/name=infrastructure
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2021-10-22T19:07:54Z
  Generation:          2
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        f:commonName:
        f:dnsNames:
        f:issuerRef:
          f:kind:
          f:name:
        f:secretName:
        f:secretTemplate:
          f:annotations:
            f:reflector.v1.k8s.emberstack.com/secret-reflection-allowed:
            f:reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled:
            f:reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces:
    Manager:      kustomize-controller
    Operation:    Apply
    Time:         2021-10-23T09:12:54Z
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:revision:
    Manager:         controller
    Operation:       Update
    Time:            2021-10-23T09:14:12Z
  Resource Version:  1440704
  UID:               84b7fa0f-bb18-4729-9d92-444d0137123e
Spec:
  Common Name:  example.com
  Dns Names:
    example.com
    *.example.com
  Issuer Ref:
    Kind:       ClusterIssuer
    Name:       letsencrypt-production
  Secret Name:  wildcard-example-com
  Secret Template:
    Annotations:
      reflector.v1.k8s.emberstack.com/secret-reflection-allowed:          true
      reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled:     true
      reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces:  public,home
Status:
  Conditions:
    Last Transition Time:  2021-10-23T09:14:12Z
    Message:               Certificate is up to date and has not expired
    Observed Generation:   2
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2022-01-21T08:14:11Z
  Not Before:              2021-10-23T08:14:12Z
  Renewal Time:            2021-12-22T08:14:11Z
  Revision:                2
Events:
  Type    Reason     Age    From          Message
  ----    ------     ----   ----          -------
  Normal  Issuing    6m1s   cert-manager  Issuing certificate as Secret does not exist
  Normal  Generated  6m1s   cert-manager  Stored new private key in temporary Secret resource "wildcard-example-com-b765h"
  Normal  Requested  6m1s   cert-manager  Created new CertificateRequest resource "wildcard-example-com-pv9br"
  Normal  Issuing    5m59s  cert-manager  The certificate has been successfully issued
```

However the namespaces public and home do not contain the certificate after I restarted the reflector pod:

```
kubectl get secret -n public
--------------------------------------------------------------
NAME                               TYPE                                  DATA   AGE
default-token-z4sr6                kubernetes.io/service-account-token   3      2d16h
mariadb-root-password              Opaque                                1      2d16h
mariadb-token-b95v7                kubernetes.io/service-account-token   3      2d
nextcloud                          Opaque                                2      2d
nextcloud-database-credentials     Opaque                                2      2d16h
sftp-credentials                   Opaque                                3      2d16h
sh.helm.release.v1.mariadb.v1      helm.sh/release.v1                    1      2d
sh.helm.release.v1.mariadb.v2      helm.sh/release.v1                    1      2d
sh.helm.release.v1.mariadb.v3      helm.sh/release.v1                    1      2d
sh.helm.release.v1.mariadb.v4      helm.sh/release.v1                    1      16h
sh.helm.release.v1.nextcloud.v1    helm.sh/release.v1                    1      2d
sh.helm.release.v1.nextcloud.v2    helm.sh/release.v1                    1      2d
sh.helm.release.v1.nextcloud.v3    helm.sh/release.v1                    1      16h
sh.helm.release.v1.phpmyadmin.v1   helm.sh/release.v1                    1      16h
sh.helm.release.v1.phpmyadmin.v2   helm.sh/release.v1                    1      16h
```

Pod logs of reflector stay rather empty:
```
2021-10-23 09:15:53.994 +00:00 [INF] () Starting host
2021-10-23 09:15:54.822 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2021-10-23 09:15:54.953 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2021-10-23 09:15:54.970 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
```

helm release:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts
      chart: reflector
      version: 6.0.18
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
        namespace: flux-system
      interval: 5m
  values:
```
