### ISSUE TITLE
are annotation needed on both ends?

### ISSUE THREAD

**Issue by Vad1mo** [emberstack/kubernetes-reflector#237]
This is not cristal clear from the documentation. 

If I have this annotation set on the secret!

```yaml
"reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
"reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "dev-customerportal",
"reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "dev-customerportal"
```

do I still need to create an empty secret on the target side?

btw. make sure that this controller is listed on https://cert-manager.io/docs/faq/kubed/#syncing-arbitrary-secrets-across-namespaces-using-kubed

**Comment by winromulus** [comment]
Hi @Vad1mo 
If you want secrets to auto-reflect (basically create a secret with the same name) in the allowed auto namespaces, then you don't need to create a target.

If you manually want to create a target (and use a different name from the source), then you need annotations on the source (as you indicated in the issue, without the auto part) in order to allow reflection and on the target in order to indicate the source.

**Comment by Vad1mo** [comment]
I want that on the target side the secret/configmap is automatically created with the same name and content as on the source side.

Are those the annotation that I need to accomplish my goal?

```yaml
"reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
"reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "dev-customerportal",
"reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "dev-customerportal"
```
