### ISSUE TITLE
[Bug] Reflector cleanup of auto-mirrors results in false-positives for same-name certs in different namespaces

### ISSUE THREAD

**Issue by Vad1mo** [emberstack/kubernetes-reflector#256]
We are running reflector to copy secrets with certs from one namespace to another. 

What we actually see is that reflector (version 6.0.42) is deleting demo and prod source secrets. 

we have the following setups:

k8s Namespaces:

- dev (contains secret with cert)
- dev-ui (destination of cert)
---
- demo (contains secret with cert)
- demo-ui (destination of cert) 
---
- prod
- pord-ui

Each secret has the following annotations set:

```yaml
    "annotations": {
        "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
        "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
        "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": dev-ui,
        "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": dev-ui
```

```yaml
    "annotations": {
        "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
        "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
        "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": demo-ui,
        "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": demo-ui
```

```yaml
    "annotations": {
        "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
        "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
        "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": prod-ui,
        "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": prod-ui
```
