### ISSUE TITLE
Certificate Secret Reflection Error: "Coud not update ns/secret - Source ns/secret does not permit it"

### ISSUE THREAD

**Issue by Timothy-Dement** [emberstack/kubernetes-reflector#264]
# Overview

I'm attempting to use `reflector` to mirror a certificate secret between namespaces, but getting the following error message:

```
Coud not update <namespace>/<secret> - Source <namespace>/<secret> does not permit it
```

References:
- https://github.com/emberstack/kubernetes-reflector#cert-manager-support
- https://cert-manager.io/docs/faq/sync-secrets/

I'm using `reflector` `6.1.23` (latest) and:

```
> $ oc version
--------------
Client Version: 4.8.25
Server Version: 4.8.25
Kubernetes Version: v1.21.6+b4b4813
```

# Error Replication

I installed `reflector` with the following, which is identical to https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml except for including the `kube-system` namespace where needed:

<details><summary>Click to expand</summary><br>

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-6.1.23
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "6.1.23"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-6.1.23
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "6.1.23"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-6.1.23
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "6.1.23"
    app.kubernetes.io/managed-by: Helm
roleRef:
  kind: ClusterRole
  name: reflector
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: reflector
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-6.1.23
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "6.1.23"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflector
      app.kubernetes.io/instance: reflector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reflector
        app.kubernetes.io/instance: reflector
    spec:
      serviceAccountName: reflector
      securityContext:
        fsGroup: 2000
      containers:
        - name: reflector
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
          image: "emberstack/kubernetes-reflector:6.1.23"
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_Serilog__MinimumLevel__Default
              value: "Information"
            - name: ES_Reflector__Watcher__Timeout
              value: ""
          ports:
            - name: http
              containerPort: 25080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 10
            periodSeconds: 5
          resources:
            {}
```

</details>

The error can be seen by applying the following:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-namespace-one
---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-namespace-two
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed-issuer
  namespace: sample-namespace-one
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: sample-namespace-one
spec:
  commonName: ca-certificate
  isCA: true
  issuerRef:
    kind: Issuer
    name: self-signed-issuer
  secretName: ca-certificate
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
```

Then:

```yaml
---
apiVersion: v1
data: null
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: sample-namespace-one/ca-certificate
  name: ca-certificate
  namespace: sample-namespace-two
```

The resulting log line is:

```
2022-02-15 02:50:23.335 +00:00 [WRN] (ES.Kubernetes.Reflector.Core.SecretMirror) Could not update sample-namespace-two/ca-certificate - Source sample-namespace-one/ca-certificate does not permit it.
```

ℹ️ **NOTE:** I've also tried adding these to the `Certificate` `secretTemplate` `annotations`, but they had no effect on the error above:

- `reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ''`
- `reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'sample-namespace-two'`
- `reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'sample-namespace-one,sample-namespace-two'`

**Comment by Timothy-Dement** [comment]
🤔 It seems the `reflection-auto-enabled` isn't working for me either, if I change the annotations for the `Certificate` to:

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: sample-namespace-one
spec:
  commonName: ca-certificate
  isCA: true
  issuerRef:
    kind: Issuer
    name: self-signed-issuer
  secretName: ca-certificate
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'sample-namespace-1,sample-namespace-two'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'sample-namespace-1,sample-namespace-2'
```

I would expect to see the `ca-certificate` secret in `sample-namespace-one` and `sample-namespace-two`, but only have the former:

```
> $ oc get secret --all-namespaces | grep -E 'NAME|ca-certificate'
NAMESPACE                NAME              TYPE                 DATA    AGE
sample-namespace-one     ca-certificate    kubernetes.io/tls    3       3m3s
```
