### ISSUE TITLE
Is it possible to use the k8s reflector with External Secrets?

### ISSUE THREAD

**Issue by mvoitko** [emberstack/kubernetes-reflector#279]
Is it possible to use the k8s reflector with [External Secrets](https://github.com/external-secrets/external-secrets)?

**Comment by winromulus** [comment]
I would need to investigate this. I don't have an environment for this.
Can you explain more on how you would see this work?

**Comment by druesendieb** [comment]
We've used this in the past with KES (the predecessor of what you've linked) by adding the External Secrets annotations to `spec.template.metadata.annotations` in the `ExternalSecret` object. After having a quick look at ESO, try setting this at `spec.target.template.metadata.annotations`

**Comment by Rohmilchkaese** [comment]
I can in fact confirm, that this works perfectly fine

**Comment by szechp** [comment]
yes, this works:
here is an example for dockerconfig json. annotations get carried over via templating as well:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: some-name
  namespace: default
spec:
  refreshInterval: 3600s
  secretStoreRef:
    name: your-backend
    kind: whatever-you-use
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"git.openforce.com:4567":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ list .username .password | join ":" | b64enc }}"}}}'
      templateFrom:
        - target: Annotations
          literal: |
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "namespace-where-you-want-to-reflect"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: some-key
        property: docker-repo-password
    - secretKey: username
      remoteRef:
        key: some-key
        property: some-username
```

**Comment by szechp** [comment]
yes this works. here's an example for dockerconfig.json. this even carries over annotations via templating:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: some-name
  namespace: default
spec:
  refreshInterval: 3600s
  secretStoreRef:
    name: your-backend
    kind: whatever-you-use
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"your.repo.url":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ list .username .password | join ":" | b64enc }}"}}}'
      templateFrom:
        - target: Annotations
          literal: |
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "namespace-where-you-want-to-reflect"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: some-key
        property: docker-repo-password
    - secretKey: username
      remoteRef:
        key: some-key
        property: some-username
```
