### ISSUE TITLE
Exlude namespace support

### ISSUE THREAD

**Issue by ngnix** [emberstack/kubernetes-reflector#321]
HI !

Can you added new feature - exclude/blacklist namespaces from secret mirroring, like this:

` reflector.v1.k8s.emberstack.com/reflection-exclude-ns: default,kube-system,kube-public,kube-node-lease`

And

` reflector.v1.k8s.emberstack.com/reflection-exclude-ns-regexp: kube-*`

Thanks!

**Comment by jan-di** [comment]
You can currently do this by using a RegEx with a negative lookahead:

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "^(?!(?:default|kube-system|kube-node-lease|kube-public)$).*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "" # all namespaces, filtered by allowed namespaces
```
