### ISSUE TITLE
[Ehancement] Restrict cluster role to strictly needed permissions

### ISSUE THREAD

**Issue by sfynx** [emberstack/kubernetes-reflector#34]
The operator currently has these permissions inside the cluster:
```
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["*"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["*"]
```
I think we should be able to cut these down, also the verbs (although less strict than a project like mittwald/kubernetes-replicator as we also create and delete our replicated resources).
