### ISSUE TITLE
`OutOfSync` in argocd

### ISSUE THREAD

**Issue by sh-cho** [emberstack/kubernetes-reflector#378]
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mirror-wildcard-foo-com-tls
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "default/default-wildcard-foo-com-tls"
data:
```
Because desired state of `Secret.data` is null so argocd sync status is out-of-sync and if I do sync, secret is updated with null data.

Any advice?

**Comment by sh-cho** [comment]
```yaml
ignoreDifferences:
  - kind: Secret
    name: mirror-wildcard-foo-com-tls
    jsonPointers:
      - /data
      - /data/tls.crt
      - /data/tls.key
```

I added this `ignoreDifferences` option to argocd application and works OK. Since it's not reflector's problem(maybe?) I'm closing this issue.
