### ISSUE TITLE
[QUESTION] values.yaml variables & certificate reflectors

### ISSUE THREAD

**Issue by boomam** [emberstack/kubernetes-reflector#395]
Hi,  
Two questions in one -  
1. The values.yaml has an entry for log level, listing the default as 'informational', can you define the exact verbiage you use for the other log levels please?  
Attempted 'error' as another common one, but all it does it ensure nothing gets logged.  
&nbsp;  
3. Are certificates (via cert-manager) expected to be something that is synced with this?  
I ask as i have a test certificate setup with the relevant annotations (details below), but it doesnt get sync'd.  
So I'm not sure if its something that's possible or not? Reading around a few issues, there's suggestions that it is?  

Pod Reflector Log -  
```
[INF] () Starting host
[INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
[INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
[INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
[INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:33:30.6635494. Faulted: False.
[INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
[INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:34:14.2421531. Faulted: False.
[INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
[INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:37:40.4782528. Faulted: False.
[INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
```
&nbsp;  
Deployment values.yaml -  
```
configuration:
  logging:
    minimumLevel: Information
cron:
  activeDeadlineSeconds: 600
  enabled: false
  schedule: '*/15 * * * *'
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
```
&nbsp;  
Test certificate yaml -  (built based on guidance/examples [here](https://artifacthub.io/packages/helm/emberstack/reflector#cert-manager-support) and [here](https://github.com/emberstack/kubernetes-reflector#cert-manager-support)).  
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-domain-com
  namespace: cert-manager
spec:
  secretName: test-domain-com
  dnsNames:
  - "test.domain.com"
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "test-namespace"
```

**Comment by bonddim** [comment]
1. Project uses [serilog/serilog](https://github.com/serilog/serilog) for logging.
   According to their [docs](https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level) you may configure next levels:

Level | Description
-- | --
Verbose | Verbose is the noisiest level, rarely (if ever) enabled for a production app.
Debug | Debug is used for internal system events that are not necessarily  observable from the outside, but useful when determining how something  happened.
Information | Information events describe things happening in the system that  correspond to its responsibilities and functions. Generally these are  the observable actions the system can perform.
Warning | When service is degraded, endangered, or may be behaving outside of its expected parameters, Warning level events are used.
Error | When functionality is unavailable or expectations broken, an Error event is used.
Fatal | The most critical level, Fatal events demand immediate attention.

2. Secrets generated from certificates with templates are synced.
    If you want automatic(push) sync:
    ```yaml
    ...
    secret-name: test-domain-com
    secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "test-namespace"
    ```
    for pull sync:
    - leave annotations as in your example
    - create destination secret in `test-namespace`
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: mirror-secret
      namespace: test-namespace
      annotations:
       reflector.v1.k8s.emberstack.com/reflects: "cert-manager/test-domain-com"
    data: {}
    ```
  This is documented on project's main [page](https://github.com/emberstack/kubernetes-reflector/tree/main?tab=readme-ov-file#usage)
