### ISSUE TITLE
FeatureRequests: (1) Key rename and (2) cross-object mirror reflection

### ISSUE THREAD

**Issue by lazarusllong** [emberstack/kubernetes-reflector#396]
### 0. Motivation
On _OpenShift_ a custom certificate to serve the default ingress requires two different objects; a custom CA and a custom TLS certificate:
- The custom CA is stored in a _configMap_ under the key **ca-bundle.crt**.
- The custom certificate is a regular _TLS secret_ with the certificate chain under key **tls.crt**.

The custom certificate on this scenario has a _RFC1422_ compliant full certificate chain, though _OpenShift_ ignores it and instead uses the chain from the custom CA key **ca-bundle.crt**.

The custom CA _configMap_ is currently being generated by manually exporting the **tls.key** content from the custom certificate _secret_ and importing it into the key **ca-bundle.crt**.

Automating this task isn't currently supported by _Reflector_ since it doesn't support neither key renaming nor cross-object mirroring.

Though being suggested here together these are two _distinct_ and _independent_ feature requests:

### 1. Key renaming:
Addition of a new annotation on the _mirror_ object (i.e. **_reflector.v1.k8s.emberstack.com/key-mapping: "source-key1:mirror-key1,source-key2:mirror-key2 ..."_**) for something like:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mirror-secret
  namespace: default
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "default/source-secret"
    reflector.v1.k8s.emberstack.com/key-mapping: "src.key:dst.key,src.other:dst.other"
data:
  dst.key: ...
  dst.other: ...
...
```

### 2. Cross-object mirroring:
Addition of a new annotation on the _mirror_ object (i.e. **_reflector.v1.k8s.emberstack.com/source-type: "secret|configMap"_**) for something like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-cm
  namespace: default
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "default/source-secret"
    reflector.v1.k8s.emberstack.com/source-type: "secret"
data:
...
```

### 3. For a full picture of how the specific scenario that motivated these feature requests would possibly end up being:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: custom-tls-certificate
  namespace: openshift-config
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openshift-config"
data:
  tls.key: ...
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca
  namespace: openshift-config
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "openshift-config/custom-tls-certificate"
    reflector.v1.k8s.emberstack.com/source-type: "secret"
    reflector.v1.k8s.emberstack.com/key-mapping: "tls.key:ca-bundle.key"
data:
  ca-bundle.key: |
...
```

### This specific scenario being described would need both these features, though their individual merits are foreseeable.

Thank you very much, for your attention.
