### ISSUE TITLE
Wrong type on the Secret used as dockerconfigjson

### ISSUE THREAD

**Issue by cotoman** [emberstack/kubernetes-reflector#397]
Hello! We're trying to use reflector as a way to copy our registry key secret across multiple namespaces. Now it is deployed to the target namespace as expected. We suspect that due to the fact that its type is `Opaque` and not `kubernetes.io/dockerconfigjson`, multiple pods are failing to pull our private images.

Is there an annotation that I've missed, which would cover this scenario?

```
apiVersion: v1
kind: Secret
metadata:
 name: key
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "source-namespace/key"
type: kubernetes.io/dockerconfigjson ->> can't be added directly in the target secret
```

Thanks
