### ISSUE TITLE
Secret with binaryData

### ISSUE THREAD

**Issue by dbpolito** [emberstack/kubernetes-reflector#40]
I'm trying to sync a `registry cred` secret across namespaces, looking at here https://github.com/emberstack/kubernetes-reflector#3-done it seems it do not sync secret with `dataBinary` by design, is there any reason for it?

My secret:

```yaml
apiVersion: v1
data:
  .dockerconfigjson: <removed>
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-fwd
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces: "(dev|staging|prod)-[a-zA-Z0-9-_]+"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "(dev|staging|prod)-[a-zA-Z0-9-_]+"
type: kubernetes.io/dockerconfigjson
```

Am i doing something wrong? I got reflector working on my cluster for certificates with these annotations and logs looks ok.
