### ISSUE TITLE
Fresh Deployment Fails to Start Reflector Pod

### ISSUE THREAD

**Issue by j0sh3rs** [emberstack/kubernetes-reflector#434]
Issue: Attempting to deploy a fresh instance of reflector (Having never used it before), into its own namespace, with the below configs, results in a pod CrashLoop.

Pod Error:
```shell
$ k logs -f -n reflector reflector-7f8f8dff88-drz8f 
Failed to create CoreCLR, HRESULT: 0x8007000E
```

Flux HelmRelease configuration:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: reflector
      version: 7.1.262
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: emberstack-charts
      interval: 1h
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      readOnlyRootFilesystem: true
```
