### ISSUE TITLE
Target autocreation

### ISSUE THREAD

**Issue by whyvez** [emberstack/kubernetes-reflector#44]
I just started using `kubernetes-reflector` and I was expecting target resources to get automatically populated with their source values (i.e. secret data) when they are created but it didn't.

**Source:**
```
cat <<EOF | kubectl apply -n default -f -
apiVersion: v1
kind: Secret
metadata:
  name: secret-pg-password
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "*"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "*"
type: Opaque
data:
  pgpassword: "base64-password"
EOF
```

**Target:**
```
cat <<EOF | kubectl apply -n other-namespace -f -
apiVersion: v1
kind: Secret
metadata:
  name: secret-pg-password
  annotations:
   reflector.v1.k8s.emberstack.com/reflects: "default/secret-pg-password"
type: Opaque
data:
  pgpassword: ""
EOF
```

I first create the source secret and then the target secret. I would expect that as soon as I create the target secret for the values form the source to get copied over to the target. Is this not the desired behavior?

**Comment by winromulus** [comment]
@whyvez can you share the reflector logs please?

**Comment by whyvez** [comment]
I had a look at the logs and figured out my problem.

I updated my sources to be like:

```
cat <<EOF | kubectl apply -n default -f -
apiVersion: v1
kind: Secret
metadata:
  name: secret-pg-password
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
data:
  pgpassword: "base64-password"
EOF
```

Looks like both namespace list annotations don't accept wildcard (*).

Thank you!
