### ISSUE TITLE
Secret Replication Takes Over 5-10 Minutes After Creating a New Namespace

### ISSUE THREAD

**Issue by suyog1pathak** [emberstack/kubernetes-reflector#486]
After creating a new namespace, the replication of secrets is taking an unusually long time—typically more than 5-6 minutes. This delay affects the timely provisioning of workloads that rely on these secrets.

Expected Behavior:
Secrets should be replicated promptly (within a few seconds to a minute) after a new namespace is created.

Actual Behavior:
The replication process is significantly delayed, impacting workload deployments.

e.g
```
apiVersion: v1
data:
  .dockerconfigjson: xxxxxxxx
kind: Secret
metadata:
  name: testcreds
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
 namespace: kube-system
type: kubernetes.io/dockerconfigjson

```
