### ISSUE TITLE
Problem in replicating secrets from ingress

### ISSUE THREAD

**Issue by slink2111** [emberstack/kubernetes-reflector#501]
Pulled: ghcr.io/emberstack/helm-charts/reflector:9.1.2

I am having the following configuration, 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  # Cert-manager for Let's Encrypt
    cert-manager.io/secret-template: |
      {"annotations": {"reflector.v1.k8s.emberstack.com/reflection-allowed": "true", "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "default", "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true", "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "default"}}
spec:
...
```

i have multiple secrets that are being created but not replicated in the default namespace, 

The only log in the reflector pod is 

2025-05-03 01:48:02.551 +00:00 [INF] (ES.Kubernetes.Reflector.Watchers.NamespaceWatcher) Requesting V1Namespace resources
2025-05-03 01:48:02.607 +00:00 [INF] (ES.Kubernetes.Reflector.Watchers.SecretWatcher) Requesting V1Secret resources
2025-05-03 01:48:02.637 +00:00 [INF] (ES.Kubernetes.Reflector.Watchers.ConfigMapWatcher) Requesting V1ConfigMap resources
2025-05-03 01:48:02.678 +00:00 [INF] (Microsoft.Hosting.Lifetime) Now listening on: http://[::]:8080
2025-05-03 01:48:02.678 +00:00 [INF] (Microsoft.Hosting.Lifetime) Application started. Press Ctrl+C to shut down.
2025-05-03 01:48:02.678 +00:00 [INF] (Microsoft.Hosting.Lifetime) Hosting environment: Production
2025-05-03 01:48:02.678 +00:00 [INF] (Microsoft.Hosting.Lifetime) Content root path: /app

Using MicroK8s v1.32.3 revision 8148
