### ISSUE TITLE
ConfigMap only mode?

### ISSUE THREAD

**Issue by zar3bski** [emberstack/kubernetes-reflector#516]
I really appreciate this component but I am slightly paranoid and I wondered it is or could be possible to make it watch only configMap and **ignore Secrets** (sharing of which should rely on a more traceable and controlled tool such as a vault). I tried to restrict the resources in the `ClusterRole` but it ended in a lot of error. 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-9.1.7
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "9.1.7"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
```
Exposing this feature through a ENV vars such as `ES_Reflector__Watcher__Resources` (default `Secrets,ConfigMaps`) would be an elegant way to tune the behavior
