### ISSUE TITLE
Set annotation `reflection-allowed: "true"` and `reflection-auto-enabled:"true"` implicitly

### ISSUE THREAD

**Issue by Brice187** [emberstack/kubernetes-reflector#521]
Currently I have to annotate secrets and configmaps in this fashion:
```
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: example-app,example-service-.*
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: example-app
  name: example-secret
  namespace: example-app
type: Opaque
data:
  password: ZG8teW91LXJlYWxseS10aGluay1pLXBhc3RlLXNlbnNpdGl2ZS1jcmVkZW50aWFscy1vbi1naXRodWItaXNzdWVz
  username: bG9s
```
Because I added namespaces to `allowed-namespaces` and `auto-namespaces`, the bool value for each could imho be ommitted.
