### ISSUE TITLE
kubernetes-reflector stops reflecting

### ISSUE THREAD

**Issue by samedguener** [emberstack/kubernetes-reflector#88]
Hi all,

I am currently using kubernetes-reflector with version `5.3.16` on Kubernetes `1.18.5`. I have a namespace, where I manage secrets with Terraform and replicate those secrets into respective service namespaces.

In the beginning the reflector manages to reflect the secrets, but after some while it stops reflecting it.
These are the last logs, another deployment won't trigger reflector to reflect.

```
2020-09-17 13:33:04.360 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.SecretMirror) Secret service/container-registry-secret reflected version (36305740) matches source global-secrets/container-registry-secret version (36305740)
2020-09-17 13:33:04.535 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.SecretMirror) Secret service/container-registry-secret reflected version (36305740) matches source global-secrets/container-registry-secret version (36305740)
```

Here are some of my resources:

Target (managed by Helm)
```yaml
# This will copy the ssl certificate from the global-secrets namespace
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: global-secrets/letsencrypt-wildcard-cert
type: kubernetes.io/tls
data:
    tls.key: e30K
    tls.crt: e30K
```

Source (Managed by Helm through Terraform)
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-wildcard-cert
  namespace: global-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflected-version: ""
spec:
  secretName: letsencrypt-wildcard-cert
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
```

This happens also for any other type of secret. In case of the Certificate, reflector annotates it correctly but also fails to reflect. I am using cert-manager `0.16.1`.

Any idea what to do about this?

Best,
Samed
